# Generated by Django 5.2.8 on 2025-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('INTERVIEW', 'Interviewing'), ('OFFER', 'Offer Received'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
